// Team identity for card art.
//
// Every card gets real grid identity: each constructor's livery colours (2020
// F1 field + F2 teams appearing in the checklist) drive the art inside the
// card frame, so a Mercedes card reads teal and a Ferrari card reads red
// instead of the generic silhouette every card used to share.

export type TeamTheme = {
  a: string; // primary livery colour
  b: string; // secondary / shadow colour
};

// Keyed exactly as the source PDF spells the team.
const TEAM_THEMES: Record<string, TeamTheme> = {
  // 2020 Formula 1 field
  "Mercedes-AMG Petronas Formula One Team": { a: "#00d7b6", b: "#0b3a3f" },
  "Scuderia Ferrari": { a: "#e8002d", b: "#3d0a12" },
  "Aston Martin Red Bull Racing": { a: "#1e41ff", b: "#141a4d" },
  "McLaren F1® Team": { a: "#ff8700", b: "#3b2000" },
  "Renault DP World F1® Team": { a: "#ffe04f", b: "#3a3300" },
  "Scuderia AlphaTauri": { a: "#4a6fa5", b: "#152232" },
  "Alfa Romeo Racing ORLEN": { a: "#b0342f", b: "#2b1010" },
  "Haas F1® Team": { a: "#d9dee3", b: "#2a2f34" },
  "BWT Racing Point F1® Team": { a: "#f596c8", b: "#3b1630" },
  "BWT Racing Point Formula 1® Team": { a: "#f596c8", b: "#3b1630" },
  "Williams Racing": { a: "#0082fa", b: "#062a4d" },
  "Scuderia Toro Rosso": { a: "#469bff", b: "#0f2b4d" },
  "DHL Fastest Pit Stop Award": { a: "#ffcc00", b: "#3a2200" },

  // F2 teams appearing in the checklist
  "F2™ - Art Grand Prix": { a: "#c4122e", b: "#1a1a1a" },
  "F2™ - BWT HWA RACELAB": { a: "#f596c8", b: "#2b1024" },
  "F2™ - Campos Racing": { a: "#f5a623", b: "#3a2505" },
  "F2™ - Carlin": { a: "#2a5fd6", b: "#08132e" },
  "F2™ - Charouz Racing System": { a: "#e1251b", b: "#1b1b1b" },
  "F2™ - Dams": { a: "#3f6ec4", b: "#0c2340" },
  "F2™ - Hitech Grand Prix": { a: "#00a0de", b: "#0a2233" },
  "F2™ - MP Motorsport": { a: "#f47c20", b: "#3a1e08" },
  "F2™ - Prema Racing": { a: "#e4002b", b: "#2a0a0f" },
  "F2™ - Trident": { a: "#e4032e", b: "#141414" },
  "F2™ - Uni-Virtuosi Racing": { a: "#00a3e0", b: "#06283a" },
};

const FALLBACK: TeamTheme = { a: "#7f8d99", b: "#1b2229" };

export function teamTheme(team: string | null | undefined): TeamTheme {
  if (!team) return FALLBACK;
  return TEAM_THEMES[team] ?? FALLBACK;
}

// Two-letter mark used on player portraits.
export function initials(name: string): string {
  const words = name
    .replace(/[^\p{L}\p{N} ]/gu, " ")
    .split(/\s+/)
    .filter(Boolean);
  if (words.length === 0) return "?";
  if (words.length === 1) return words[0].slice(0, 2).toUpperCase();
  return (words[0][0] + words[words.length - 1][0]).toUpperCase();
}

export type ArtKind = "racer" | "car" | "crest";

// Sections that picture a car rather than a driver.
const CAR_SECTIONS = new Set(["f1-cars", "f2-cars"]);

const SECTION_SLUG_BY_NAME: Record<string, string> = {
  "F1 RACERS": "f1-racers",
  "F1 CARS": "f1-cars",
  "F2 RACERS": "f2-racers",
  "F2 CARS": "f2-cars",
  "F1 CREW": "f1-crew",
  "F2 CREW": "f2-crew",
  "TEAM LOGOS": "team-logos",
  "GRAND PRIX WINNERS": "grand-prix-winners",
  "GRAND PRIX DRIVER OF THE DAY": "grand-prix-driver-of-the-day",
  "F1 AWARD WINNERS": "f1-award-winners",
  "F1 FRESHEST": "f1-freshest",
  "TRACK TAGS": "track-tags",
  "1954 TOPPS WORLD ON WHEELS": "world-on-wheels",
  "BASE CARD IMAGE VARIATIONS": "base-card-image-variations",
  "CHROME AUTOGRAPH VARIATIONS": "chrome-autograph-variations",
};

export function artKind(
  sectionSlug: string | undefined,
  kind: string | undefined,
): ArtKind {
  if (sectionSlug && CAR_SECTIONS.has(sectionSlug)) return "car";
  if (kind === "collection") return "crest";
  return "racer";
}

// Edition variants carry either a checklist section name (the "Official
// Checklist" tier) or a parallel name, so the art is resolved both ways.
export function variantArt(variant: string): ArtKind {
  const slug = SECTION_SLUG_BY_NAME[variant.toUpperCase()];
  if (slug) return artKind(slug, "person");
  if (variant === "World on Wheels") return "car";
  if (variant === "Track Tags") return "crest";
  return "racer";
}

// ---------------------------------------------------------------------------
// Team marks — abstract geometry drawn in each constructor's livery colours and
// generated by scripts/gen-team-marks.ts into public/img/teams/*.svg.
//
// These deliberately are NOT manufacturer artwork: the site used to ship PNGs
// mirrored from an AGPL-licensed repository, and reproducing team marks would
// lean on trademarks the MIT/AGPL software licences do not grant (see
// THIRD_PARTY_NOTICES.md). Keyed by every spelling the site uses: the 2020
// checklist spells them with sponsor prefixes, the archive data carries the
// Ergast entry-list names, so both families map to the same file.
// ---------------------------------------------------------------------------

const TEAM_LOGOS: Record<string, string> = {
  // Ergast / archive names
  Mercedes: "/img/teams/mercedes.svg",
  "Red Bull": "/img/teams/red-bull-racing.svg",
  "Oracle Red Bull Racing": "/img/teams/red-bull-racing.svg",
  Ferrari: "/img/teams/ferrari.svg",
  McLaren: "/img/teams/mclaren.svg",
  "Alpine F1 Team": "/img/teams/alpine.svg",
  Alpine: "/img/teams/alpine.svg",
  "Aston Martin": "/img/teams/aston-martin.svg",
  Williams: "/img/teams/williams.svg",
  "Haas F1 Team": "/img/teams/haas-f1-team.svg",
  "Moneygram Haas F1 Team": "/img/teams/haas-f1-team.svg",
  "RB F1 Team": "/img/teams/racing-bulls.svg",
  "Racing Bulls": "/img/teams/racing-bulls.svg",
  Sauber: "/img/teams/kick-sauber.svg",
  "Kick Sauber": "/img/teams/kick-sauber.svg",
  "Alfa Romeo": "/img/teams/kick-sauber.svg",

  // 2020 checklist spellings
  "Mercedes-AMG Petronas Formula One Team": "/img/teams/mercedes.svg",
  "Scuderia Ferrari": "/img/teams/ferrari.svg",
  "Aston Martin Red Bull Racing": "/img/teams/red-bull-racing.svg",
  "McLaren F1® Team": "/img/teams/mclaren.svg",
  "Renault DP World F1® Team": "/img/teams/alpine.svg",
  "Scuderia AlphaTauri": "/img/teams/racing-bulls.svg",
  "Alfa Romeo Racing ORLEN": "/img/teams/kick-sauber.svg",
  "Haas F1® Team": "/img/teams/haas-f1-team.svg",
  "BWT Racing Point F1® Team": "/img/teams/aston-martin.svg",
  "BWT Racing Point Formula 1® Team": "/img/teams/aston-martin.svg",
  "Williams Racing": "/img/teams/williams.svg",
  "Scuderia Toro Rosso": "/img/teams/racing-bulls.svg",
};

/** Transparent team mark, or null when no official logo is on file. */
export function teamLogo(team: string | null | undefined): string | null {
  if (!team) return null;
  return TEAM_LOGOS[team] ?? null;
}
