// Single seam between the UI and its data source.
//
// MOCK MODE (default): every endpoint resolves to /mock/*.json, generated by
// scripts/gen-market-mock.mjs. Filtering / sorting / pagination run in the
// browser (src/market/query.ts) because a static file cannot answer a query.
//
// REAL API: set NEXT_PUBLIC_MARKET_API=https://api.example.com/v1 and implement
// the same six resources in src/market/api.ts (fetchQuery instead of fetchFile).
// No component changes.

export const API_BASE = process.env.NEXT_PUBLIC_MARKET_API ?? "/mock";

const IS_PROD = process.env.NODE_ENV === "production";
const IS_MOCK = API_BASE === "/mock";

/**
 * True while reads come from /mock/*.json. In this mode filtering, sorting and
 * pagination run in the browser (src/market/query.ts) because a static file
 * cannot answer a query. Against a real API they move to the server and
 * query.ts drops out of the read path. See docs/BACKEND.md.
 */
export const MOCK_MODE = IS_MOCK;

/** Simulated network latency for list/detail reads (ms). 0 against a real API. */
export const READ_LATENCY_MS = Number(
  process.env.NEXT_PUBLIC_MOCK_LATENCY ?? (IS_MOCK ? (IS_PROD ? 150 : 260) : 0),
);

/** Simulated latency for trade actions (ms). */
export const WRITE_LATENCY_MS = 900;

/**
 * Buy / Sell are FROZEN: the buttons render, explain themselves, and refuse to
 * fire. The whole flow underneath is implemented and can be exercised by
 * appending ?trade=1 to any market URL — but only where debug switches are
 * enabled (see DEV_SWITCHES).
 */
export const TRADE_FROZEN_DEFAULT = true;

export const TRADE_QUERY_PARAM = "trade";

/**
 * Query-string debug switches (?trade=1, ?fail=1) are a review tool, not a
 * feature: a visitor must never be able to turn a frozen market into a "live"
 * one, or to force error states, just by editing the URL. They work in `next
 * dev` and in any build that opts in with NEXT_PUBLIC_DEV_SWITCHES=1.
 */
export const DEV_SWITCHES = !IS_PROD || process.env.NEXT_PUBLIC_DEV_SWITCHES === "1";

/**
 * Copy for every frozen control. Outside a dev build the ?trade=1 switch does
 * not exist, so the UI must stop advertising it.
 */
export const TRADE_HINT = DEV_SWITCHES
  ? "已冻结（?trade=1 可开启演练）"
  : "尚未开放";

export function tradeEnabled(search: string | null): boolean {
  if (!DEV_SWITCHES) return !TRADE_FROZEN_DEFAULT;
  if (!search) return !TRADE_FROZEN_DEFAULT;
  const p = new URLSearchParams(search);
  return p.get(TRADE_QUERY_PARAM) === "1";
}

/** ?fail=1 forces the next read to reject, so error states are reviewable. */
export function failInjected(search: string | null): boolean {
  if (!DEV_SWITCHES) return false;
  if (!search) return false;
  return new URLSearchParams(search).get("fail") === "1";
}

export const CURRENCY = "CNY";
export const CURRENCY_SYMBOL = "¥";
